INSERT INTO `Character`(LatestAlias, FirstName, LastName, `Status`) VALUES
    ('Iron Man', 'Anthony', 'Stark', 'Deceased'),
    ('War Machine', 'James', 'Rhodes', 'Alive'),
    ('Pepper Potts', 'Virginia', 'Potts', 'Alive'),
    ('Happy Hogan', 'Harold', 'Hogan', 'Alive'),
    ('White Vision', 'Vision', NULL, 'Active'),
    ('Nick Fury', 'Nicholas', 'Fury', 'Alive'),
    ('Watcher Informant', 'Stan', 'Lee', 'Alive'),
    ('Abomination', 'Emil', 'Blonsky', 'Alive'),
    ('Thunderbolt Ross', 'Thaddeus', 'Ross', 'Alive'),
    ('Black Widow', 'Natalia', 'Romanoff', 'Deceased'),
    ('Thunder', 'Thor', 'Odinson', 'Alive'),
    ('Loki', 'Loki', 'Laufeyson', 'Deceased'),
    ('Loki (2012 Time Heist)', 'Loki', 'Laufeyson', 'Alive'),
    ('Sylvie (Variant L1190)', 'Sylvie', 'Laufeydottir', 'Alive'),
    ('Heimdall', 'Heimdall', NULL, 'Deceased'),
    ('Mighty Thor', 'Jane', 'Foster', 'Deceased'),
    ('Hawkeye', 'Clinton', 'Barton', 'Alive'),
    ('Steve Rogers', 'Steven', 'Rogers', 'Alive'),
    ('White Wolf', 'James', 'Barnes', 'Alive'),
    ('Thanos', 'Thanos', NULL, 'Deceased'),
    ('Collector', 'Taneleer', 'Tivan', 'Alive'),
    ('Captain America', 'Samuel', 'Wilson', 'Alive'),
    ('Scarlet Witch', 'Wanda', 'Maximoff', NULL),
    ('Star-Lord', 'Peter', 'Quill', 'Alive'),
    ('Rocket Racoon', '89P13', NULL, 'Alive'),
    ('Groot', 'Groot', NULL, 'Alive'),
    ('Drax the Destroyer', 'Drax', NULL, 'Alive'),
    ('Gamora', 'Gamora', 'Zen Whoberi', 'Deceased'),
    ('Gamora (2014 Time Heist)', 'Gamora', 'Zen Whoberi', 'Alive'),
    ('Nebula', 'Nebula', NULL, 'Alive'),
    ('Ultron', 'Ultron', NULL, 'Destroyed'),
    ('Ant-Man', 'Scott', 'Lang', 'Alive'),
    ('Wasp', 'Hope', 'van Dyne', 'Alive'),
    ('Hank Pym', 'Henry', 'Pym', 'Alive'),
    ('Yellowjacket', 'Darren', 'Cross', NULL),
    ('T\'Challa', 'T\'Challa', NULL, 'Deceased'),
    ('Baron Zemo', 'Helmut', 'Zemo', 'Alive'),
    ('Doctor Strange', 'Steven', 'Strange', 'Alive'),
    ('Wong', 'Wong', NULL, 'Alive'),
    ('Mantis', 'Mantis', NULL, 'Alive'),
    ('Vulture', 'Adrian', 'Toomes', 'Alive'),
    ('Black Panther', 'Shuri', NULL, 'Alive'),
    ('Midnight Angel', 'Okoye', NULL, 'Alive'),
    ('M\'Baku', 'M\'Baku', NULL, 'Alive'),
    ('Erik Killmonger', 'N\'Jadaka', NULL, 'Deceased'),
    ('Captain Marvel', 'Carol', 'Danvers', 'Alive'),
    ('Talos', 'Talos', NULL, 'Alive'),
    ('Mysterio', 'Quentin', 'Beck', 'Deceased'),
    ('J. Jonah Jameson', 'John', 'Jameson', 'Alive'),
    ('U.S. Agent', 'Johnathan', 'Walker', 'Alive'),
    ('Val', 'Valentina', 'de Fontaine', 'Alive'),
    ('Mobius', 'Mobius', 'Mobius', 'Alive'),
    ('He Who Remains', 'Nathaniel', 'Richards', 'Deceased'),
    ('Kang', 'Nathaniel', 'Richards', 'Alive'),
    ('Yelena Belova', 'Yelena', 'Belova', 'Alive'),
    ('Red Guardian', 'Alexei', 'Shostakov', 'Alive'),
    ('Taskmaster', 'Antonia', 'Dreykov', 'Alive'),
    ('The Watcher', 'Uatu', NULL, 'Alive'),
    ('Shang-Chi', 'Xu Shang-Chi', NULL, 'Alive'),
    ('Sersi', 'Sersi', NULL, 'Alive'),
    ('Blade', 'Eric', 'Brooks', 'Alive'),
    ('Kate Bishop', 'Katherine', 'Bishop', 'Alive'),
    ('Kingpin', 'Wilson', 'Fisk', 'Alive'),
    ('Daredevil', 'Matthew', 'Murdock', 'Alive'),
    ('Moon Knight', 'Marc', 'Spector', 'Alive'),
    ('America Chavez', 'America', 'Chavez', 'Alive'),
    ('Ms. Marvel', 'Kamala', 'Khan', 'Alive'),
    ('Gorr the God Butcher', 'Gorr', NULL, 'Deceased'),
    ('She-Hulk', 'Jennifer', 'Walters', 'Alive'),
    ('Werewolf by Night', 'Jack', 'Russel', 'Alive'),
    ('Namor', 'K\'uk\'ulkan', NULL, 'Alive'),
    ('Ironheart', 'Riri', 'Williams', 'Alive'),
    ('Kang the Conqueror', 'Nathaniel', 'Richards', 'Deceased'),
    ('Rama-Tut', 'Nathaniel', 'Richards', 'Alive'),
    ('Immortus', 'Nathaniel', 'Richards', 'Alive'),
    ('Scarlet Centurion', 'Nathaniel', 'Richards', 'Alive'),
    ('Mister Gryphon', 'Nathaniel', 'Richards', 'Alive'),
    ('Victor Timely', 'Nathaniel', 'Richards', 'Alive');

INSERT INTO `Character` VALUES
    ('Friendly Neighborhood Spider-Man', 'Peter', 'Parker', 'Alive', '96283', 'Sony Pictures'),
    ('Green Goblin', 'Norman', 'Osborne', 'Alive', '96283', 'Sony Pictures'),
    ('The Amazing Spider-Man', 'Peter', 'Parker', 'Alive', '120703', 'Sony Pictures'),
    ('Smart Hulk', 'Robert', 'Banner', 'Alive', '199999', 'Universal Studios'),
    ('Spider-Man', 'Peter', 'Parker', 'Alive', '199999', 'Sony Pictures'),
    ('Logan', 'James', 'Howlett', 'Deceased', 'TRN414', 'Marvel Studios'),
    ('Deadpool', 'Wade', 'Wilson', 'Alive', 'TRN414', 'Marvel Studios'),
    ('Eddie Brock', 'Edward', 'Brock', 'Alive', 'TRN688', 'Sony Pictures'),
    ('Lethal Protector', 'Venom', NULL, 'Alive', 'TRN688', 'Sony Pictures'),
    ('Riot', 'Riot', NULL, 'Deceased', 'TRN688', 'Sony Pictures'),
    ('Carnage', 'Carnage', NULL, 'Deceased', 'TRN688', 'Sony Pictures'),
    ('Morbius', 'Michael', 'Morbius', 'Alive', 'TRN688', 'Sony Pictures');
